version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:206.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: CircleCIでGCPにログインする
          command: |
            GOOGLE_PROJECT_ID=door-app-prod
            GCLOUD_SERVICE_KEY=${GCLOUD_SERVICE_KEY}
            echo ${GCLOUD_SERVICE_KEY} | base64 -i --decode > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project door-app-prod
            gcloud --quiet config set compute/zone asia-northeast1-a
      - run:
          name: dockerイメージをビルドする
          command: |
            docker build -t gcr.io/$(gcloud config get-value project)/school-dashboard-api:$CIRCLE_SHA1 -f Dockerfile .
      - run:
          name: ビルドしたdockerイメージを GoogleContainerRegistory にpushする
          command: |
            gcloud docker -- push gcr.io/$(gcloud config get-value project)/school-dashboard-api:$CIRCLE_SHA1
